version: '3.8'
services:
  postgres:
    image: postgres:14.2-alpine
    container_name: servo-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - /data/pgadmin:/root/.pgadmin
    networks:
      - postgres

volumes:
  postgres:
    name: servo-db

networks:
  postgres:
    driver: bridge