export const ACCESS_TOKEN_SECRET_KEY = 'ACCESS_TOKEN_SECRET';
export const ACCESS_TOKEN_EXPIRATION_TIME_KEY = 'ACCESS_TOKEN_EXPIRATION_TIME';
export const REFRESH_TOKEN_SECRET_KEY = 'REFRESH_TOKEN_SECRET';
export const REFRESH_TOKEN_EXPIRATION_TIME_KEY =
  'REFRESH_TOKEN_EXPIRATION_TIME';
