name: Nest.js backend application CD

on:
  push:
    branches:
      - main

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Setup Node.js environment
  #     uses: actions/setup-node@v3.1.0
  #     with:
  #       node-version: 16.14.2
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Connect to VM and deploy application
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /var/www/servo.rocks/
          git pull origin dev
          yarn install --production
          pm2 restart servo-backend
      
