name: Nest.js backend application CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Connect to VM and deploy application
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        script: |
          cd /var/www/servo.rocks/
          git pull origin dev
          yarn install --production
          yarn prisma generate
          yarn prisma migrate dev
          pm2 restart servo-backend
      
